### PR TITLE
Add benchmark suite for transforms

### PR DESCRIPTION
**Pull request by Devaraj-G**
Preliminary benchmark for run-times.
Gives an output with individual columns showing the various axes of benchmarking input parameters.
```
risbo   loop       T(0004.3585s) L(0032)  beta(45.0000)  float64
risbo   loop       T(0034.9539s) L(0064)  beta(45.0000)  float64
risbo   vectorized T(0000.0000s) L(0032)  beta(45.0000)  float64
risbo   vectorized T(0000.0000s) L(0064)  beta(45.0000)  float64
risbo   jax        T(0000.0000s) L(0032)  beta(45.0000)  float64
risbo   jax        T(0000.0000s) L(0064)  beta(45.0000)  float64
trapani loop       T(0000.5543s) L(0032)  beta(45.0000)  float64
trapani loop       T(0003.9951s) L(0064)  beta(45.0000)  float64
trapani vectorized T(0000.1653s) L(0032)  beta(45.0000)  float64
trapani vectorized T(0000.5174s) L(0064)  beta(45.0000)  float64
trapani jax        T(0000.0182s) L(0032)  beta(45.0000)  float64
trapani jax        T(0000.1170s) L(0064)  beta(45.0000)  float64
turok   loop       T(0000.0480s) L(0032)  beta(45.0000)  float64
turok   loop       T(0000.1746s) L(0064)  beta(45.0000)  float64
turok   vectorized T(0000.0000s) L(0032)  beta(45.0000)  float64
turok   vectorized T(0000.0000s) L(0064)  beta(45.0000)  float64
turok   jax        T(0000.0000s) L(0032)  beta(45.0000)  float64
turok   jax        T(0000.0000s) L(0064)  beta(45.0000)  float64
```

### CODE REVIEW

**Comment by matt-graham** [comment]
Reopening as discussed in meeting with @jasonmcewen and @CosmoMatt today so we can update this to work on top of new refactored package.

**Comment by matt-graham** [comment]
@jasonmcewen and @CosmoMatt - apologies for the delay getting around to updating this PR. There are now benchmarking scripts for forward and inverse spherical + Wigner transforms, using the current interface. If the `memory_profiler` module is installed peak memory usage will be recorded alongside the timing results (this only works for main memory usage rather than GPU device memory unfortunately). The benchmark scripts also now allow manually overriding the parameter values the benchmarks are run over at the command line.

**Comment by matt-graham** [comment]
As discussed at our previous meeting I've also added @sfmig as a co-author on one of the commits so that she'll be recorded in the GitHub contributor list if this is merged.

**Comment by CosmoMatt** [comment]
@jasonmcewen We should really get this merged. It's entirely independent from the rest of the codebases there should be no conflicts and it seems to be finished + working.

**Review by CosmoMatt — APPROVED** [review]
Looks great, we should get this wrapped up.

**Comment by jasonmcewen** [comment]
Ok, if you've done a review @CosmoMatt and are happy please go ahead and merge.

**Pull request merged**
