### PR TITLE
Fix small bugs from issue 183

### PR DESCRIPTION
**Pull request by CosmoMatt**
This addresses the bugs outlined in issue #183 kindly provided by @PhilippMisofCH

- [x] dl array corrected to float64 in rotation function.
- [x] explicitly cast spin to absolute value to avoid negative power warnings in JAX in various places
- [x] change Risbo arg check function to raw string literal (r"""...) to allow LaTeX equation.

### CODE REVIEW

**Comment by CosmoMatt** [comment]
@PhilippMisofCH so long as it's ok with you, I can add you as a contributor for debugging. No worries if not.

**Comment by PhilippMisofCH** [comment]
Sure! I will continue using this library for some time and I'm happy to help with small bugs.

**Comment by CosmoMatt** [comment]
@all-contributors please add @PhilippMisofCH for bug

**Comment by CosmoMatt** [comment]
closes #183

**Pull request merged**
