### PR TITLE
Suggested little fixes (jax version, float64)

### PR DESCRIPTION
**Pull request by EiffL**
I'm opening this PR to suggest a few fixes as I see them, in particular addressing #143  #144.

Still at draft stage, because I want to check if everything works ok in the testing suite

### CODE REVIEW

**Comment by CosmoMatt** [comment]
Looks great, I've activated CI for you @EiffL, which will take some time to run - I'll also check on a GPU machine to check precision there. Then we should be able to merge. Thanks :)

**Comment by CosmoMatt** [comment]
@EiffL CI failing due to no jaxlib version. Two options, either we add a minimal requirement to requirements-core.txt or we manually install jaxlib during the tests.yml workflow. 

In practise some users may not want to manage their own version of jaxlib, so if we can include a minimal version that would be ideal I think?

**Comment by EiffL** [comment]
I think if we do it like this it should work, it would grab the current jaxlib version.

As a bonus, now s2fft works on  colab :-) 
https://colab.research.google.com/drive/12LgYB6sfljd4YYO9ifGAnCTPLEv7QOot?usp=sharing

**Comment by CosmoMatt** [comment]
Very cool, I spent a few minutes trying to get something nice set up with colab but GPU wasn't playing ball and I had other urgent work. Great this works with this update, we should add the notebook as a badge in the readme. I still need to check the change to 64bit precision on GPU but haven't had a chance yet

**Comment by CosmoMatt** [comment]
@EiffL Ok I've run some basic transforms to check 64bit precision
- [ ] without specifying 64bit, correctly defaults to 32bit
- [ ] without specifying 64bit, roundtrip error at L = 128 with MW (which should be exact) is ~1e-2
- [ ] with specifying 64bit, roundtrip error at L = 128 with MW (which should be exact) is 1e-14

Basically exactly what I predicted which is nice :sweat_smile: Otherwise though this looks like its doing some nice functionality, should pull into main. We should probably make the warning even more severe though, because 1e-2 error at 128 indicates that for larger L things could get really quite bad.

**Comment by EiffL** [comment]
Yep ok, feel free to suggest a more appropriate warning ^^

**Review by CosmoMatt — APPROVED** [review]
@EiffL Once CI's have passed we should be good to merge into main, thanks for this! Once in main we can link colab notebook into the primary readme.

**Comment by jasonmcewen** [comment]
I'd just like to review this before merging to main to keep abreast of revisions. Will take a look now...

**Review by jasonmcewen — APPROVED** [review]

**Comment by jasonmcewen** [comment]
Looks good!

**Comment by jasonmcewen** [comment]
Oh, do we need to update the notebooks to force double precision?

**Comment by jasonmcewen** [comment]
@EiffL Btw, in your notebook (https://colab.research.google.com/drive/12LgYB6sfljd4YYO9ifGAnCTPLEv7QOot?usp=sharing), if you set the healpy transforms to not do any iterations we should get identical results.

**Comment by jasonmcewen** [comment]
Oh, one other point @EiffL.  Our L is different to healpix lmax, with L=lmax+1.

**Comment by EiffL** [comment]
yep I saw that :-) I'm just using that notebook to experiment with improving the jitting time of the healpix transforms, but I think your existing notebooks are better. 
Precviously they woudlnt be able to use the GPU on colab because installing s2fft would uninstall the cuda-enable jaxlib ^^

**Comment by CosmoMatt** [comment]
> 

This is a good point, we should just add the config lines at the top of the two notebooks before merging.

**Comment by jasonmcewen** [comment]
@EiffL @CosmoMatt Is this good to merge now?  Does someone want to push the button? 

Our general process up until now has been for the person who submitted the PR to do the final merge once approved.  However, I guess that's not such a typical process now the repo is public, i.e. you're probably both expecting the other to do the merge!

**Comment by CosmoMatt** [comment]
Should be fine to merge @jasonmcewen, if you're happy with the changes to your PR @EiffL we'll merge this and close the associated issues.

**Comment by EiffL** [comment]
Go for it!

**Pull request merged**
