### PR TITLE
Iterative refinement support for JAX and NumPy forward (spherical) transform implementations

### LINKED ISSUE #139: Support HEALPix iterations to improve accuacy of transforms

### PR DESCRIPTION
**Pull request by matt-graham**
Should resolve #139 

Adds support for using `iter` keyword argument to `s2fft.forward` when using `method = "numpy"` and `method = "jax"`, using an [iterative refinement](https://en.wikipedia.org/wiki/Iterative_refinement) approach equivalent to that implemented in `healpy` to improve accuracy of forward transform (in terms of acting as the inverse of the inverse transform). 

Currently this is only added for spherical transform, and is available for all sampling types, even though in practice probably only useful for HEALPix (though `iter=1` does seem to give a small gain in accuracy for other sampling types).

### CODE REVIEW

**Comment by CosmoMatt** [comment]
@matt-graham looks great, one thing that would also be good to add is the same iterations but for the precompute versions of the transforms.

**Comment by jasonmcewen** [comment]
Good point @CosmoMatt (re precompute).  We could either do that in the current PR if quick or else do it in a next one.

**Comment by matt-graham** [comment]
@CosmoMatt - just to check by precompute versions, do you mean the `forward` and `inverse` functions in `s2fft/precompute_transforms/spherical.py`?

Also, with regards to the `precomps` argument to the `forward` and `inverse` functions in `s2fft/transforms/spherical.py` - at the moment the current implementation passes whatever value for `precomps` is passed to the top level `forward` call to both the underlying forward and inverse function calls. With `precomps = None` this works fine, but thinking about it I think this will give incorrect results if `precomps != None` as presumable the precomputed values for forward and inverse transforms differ? Also as we are making multiple calls to the forward and inverse transforms when `iter > 0` presumably it is always worth pre-computing in this situation?

**Comment by matt-graham** [comment]
- [ ] Add tests checking base transform with `iter > 0` against `healpy` + check reconstruction for large `n_iter` close to zero

**Pull request merged**
